### ISSUE TITLE
Model position doesn't fix

### ISSUE THREAD

**Issue by topolyai5** [daemontus/VuforiaLibGDX#5]
Hi!

I just found your excellent lib and I tried it. But the model doesn't fix on the image target. Here is a gif:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/2143158/21074135/f6c771b0-bef0-11e6-9f4c-f2d473613fbf.gif)

Could you please take advice for fix it?
Thanks

**Comment by daemontus** [comment]
Hmm...interesting - are you running directly the code from the repository, or some kind of modification? Because this seems like your camera matrix is not inverted correctly for some reason. (The model moves down when it should move up, etc.) 
If you are running directly the code from the repository, I would be interested in knowing these things: 
Do you have the same problem in portrait mode?
Have you tried some other device? 
I would like to know, because some cameras can behave little weird under different device rotation conditions, which would mean there is probably some condition missing in my code to handle this. (I have seen some cheap tablets that didn't handle rotation at all. I have seen devices that rotated pictures correctly, but captured only landscape video, etc.)

**Comment by topolyai5** [comment]
Thanks for your replay.
It's working in portrait mode only.

**Comment by topolyai5** [comment]
I didn't try on other devices. Just on a modern device

**Comment by daemontus** [comment]
Ok, I'll try to test it again over the weekend to see if I can replicate this :)

**Comment by boulabiar** [comment]
I have the same issue here.
I am using Vuforia in Landscape mode using 
            mActivity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
in initAR function inside AppSession.

The matrix is inverted. How to recalibrate it in landscape ?

**Comment by daemontus** [comment]
Closing due to deprecation (see readme)
